//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HappyFarmProjectAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerAddress
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public int SubDistrictId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual SubDistrict SubDistrict { get; set; }
    }
}
