//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HappyFarmProjectAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodsPriceRegion
    {
        public int Id { get; set; }
        public int GoodsId { get; set; }
        public int RegionId { get; set; }
        public int CreatedBy { get; set; }
        public decimal Price { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedAt { get; set; }
        public string RowStatus { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Good Good { get; set; }
        public virtual Region Region { get; set; }
    }
}
