//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HappyFarmProjectAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchasingDetail
    {
        public int Id { get; set; }
        public int PurchasingId { get; set; }
        public int GoodsId { get; set; }
        public int Qty { get; set; }
    
        public virtual Good Good { get; set; }
        public virtual Purchasing Purchasing { get; set; }
    }
}
