//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HappyFarmProjectAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HappyFarmPRG4Entities : DbContext
    {
        public HappyFarmPRG4Entities()
            : base("name=HappyFarmPRG4Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Banner> Banners { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<CustomerFeedback> CustomerFeedbacks { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Good> Goods { get; set; }
        public virtual DbSet<GoodsPriceRegion> GoodsPriceRegions { get; set; }
        public virtual DbSet<GoodsStockRegion> GoodsStockRegions { get; set; }
        public virtual DbSet<Promo> Promoes { get; set; }
        public virtual DbSet<Purchasing> Purchasings { get; set; }
        public virtual DbSet<PurchasingDetail> PurchasingDetails { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Selling> Sellings { get; set; }
        public virtual DbSet<SellingActivity> SellingActivities { get; set; }
        public virtual DbSet<SellingDetail> SellingDetails { get; set; }
        public virtual DbSet<SellingStatu> SellingStatus { get; set; }
        public virtual DbSet<SubDistrict> SubDistricts { get; set; }
        public virtual DbSet<UserLogin> UserLogins { get; set; }
    }
}
