//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HappyFarmProjectAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellingActivity
    {
        public int Id { get; set; }
        public int SellingId { get; set; }
        public int SellingStatusid { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Selling Selling { get; set; }
        public virtual SellingStatu SellingStatu { get; set; }
    }
}
